apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-deploy
  namespace: tp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp
  template:
    metadata:
      labels:
        app: tp
    spec:
      containers:
      - name: tp-container
        image: europe-west1-docker.pkg.dev/tp-kube-project/tp-repo/tp-app:v2
        ports:
          - containerPort: 8000
        envFrom:
          - configMapRef:
              name: tp-config
          - secretRef:
              name: tp-secret
        volumeMounts:
          - mountPath: /data
            name: data-storage
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: shared-pvc
