swagger: "2.0"
info:
  title: Flask API
  version: 1.0.0
paths:
  /hello:
    options:
      summary: "CORS support"
      operationId: helloOptions
      x-google-backend:
        address: https://flask-api-513126423995.europe-west9.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '204':
          description: "No Content"
          headers:
            Access-Control-Allow-Origin:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Headers:
              type: string
    get:
      summary: "Retourne un message Hello"
      operationId: hello
      x-google-backend:
        address: https://flask-api-513126423995.europe-west9.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        200:
          description: Message JSON
          schema:
            type: object
            properties:
              message:
                type: string
      x-google-extensions:
        cors:
          allowOrigins: ["*"]
          allowMethods: ["GET", "OPTIONS"]
          allowHeaders: ["Content-Type"]
